### ISSUE TITLE
update_databases fails

### ISSUE THREAD

**Issue by josephwb** [mkandziora/PhylUp#18]
I have set my `data/localblast.config` to point to my database (which it seems to find), but when I try to run the database updater I get the following error:
```
$ time python3 update_databases.py
Workflow runs with 8 threads.
/home/josephwb/Downloads/PhylUp/blastdb/
./data/nodes.dmp
/home/josephwb/Downloads/PhylUp/blastdb/
Traceback (most recent call last):
  File "update_databases.py", line 11, in <module>
    ncbi_data_parser.Parser(names_file=config.ncbi_parser_names_fn,
AttributeError: module 'PhylUp.config' has no attribute 'ncbi_parser_names_fn'
```
I cannot figure out what is going wrong. Is it looking for `./data/names.dmp` or something else?

**Comment by mkandziora** [comment]
I called by accident the module instead of the conf object. Fixed it - sorry for that. 

But there is a problem with the higher blast version now - which has no update_blastdb function anymore - just the perl script which I cannot call from within python. Will work on a fix.

**Comment by mkandziora** [comment]
Ok, looks like it is fixed. Blast version > 2.9 needs update_blastdb.pl instead. It might need some more cpan and json modules for linux installed to get it to run...

**Comment by josephwb** [comment]
I am still getting the same error. Was this supposed to be fixed?

I have `update_blastdb.pl` on my system. I was able to update the taxonomy db as described in the wiki, but I have no idea how to update the blast db itself. Could this be added to the wiki? Is it not possible to incorporate this into the PhylUp codebase? Can't perl just be called with `os.system(update_blastdb.pl ARGS)`?

**Comment by mkandziora** [comment]
You get the same error when running update_databases.py? Did you pull the newest version? It is updating the databases currently on my end. 

The update of the blast database will only happen if your database is older than 90 days (made more explicit in the wiki now). Added the `update_blastdb.pl nt` to the wiki under update.

**Comment by josephwb** [comment]
Yes, I have pulled and am up-to-date and still get the same error:
```
$ time python3 update_databases.py
Workflow runs with 8 threads.
/home/josephwb/Downloads/PhylUp/blastdb/
./data/nodes.dmp
/home/josephwb/Downloads/PhylUp/blastdb/
Traceback (most recent call last):
  File "update_databases.py", line 16, in <module>
    ncbi_data_parser._download_ncbi_parser(conf)
AttributeError: module 'ncbiTAXONparser.ncbi_data_parser' has no attribute '_download_ncbi_parser'
```
Is there an additional step I need to do after pulling?

**Comment by mkandziora** [comment]
Fixed.

**Comment by josephwb** [comment]
Eep still not working for me :( Too many arguments?
```
$ time python3 update_databases.py
Workflow runs with 8 threads.
/home/josephwb/Downloads/PhylUp/blastdb/
./data/nodes.dmp
/home/josephwb/Downloads/PhylUp/blastdb/
Traceback (most recent call last):
  File "update_databases.py", line 16, in <module>
    ncbi_parser._download_ncbi_parser(conf)
TypeError: _download_ncbi_parser() takes 1 positional argument but 2 were given
```

**Comment by josephwb** [comment]
Do you need further information to diagnose my problem? I cannot see where `_download_ncbi_parser` is receiving 2 arguments.

**Comment by mkandziora** [comment]
No, sorry for the delay. I was moving to a different place and wanted to make sure things are really working this time. (I havent updated my blast db again - but the rest was working now for me)
